### ISSUE TITLE
UPS Integration Environment warning email

### ISSUE THREAD

**Issue by trafnar** [Shopify/active_shipping#200]
I received this message from UPS

> This message is to inform you that you are currently using UPS Developer Kit APIs in the Customer Integration Environment (CIE), which is not intended to perform as the UPS® production environment. To avoid slow response times or planned outages, please migrate to the UPS production environment by November 25, 2014.

I believe I *am* using the production environment, and that this message might be an error. However, I'm not sure if Active Shipping provides a way to change between these environments, or how to check which environment I'm using.

Do you know?

**Comment by wvanbergen** [comment]
The following URLs are defined:

```
    TEST_URL = 'https://wwwcie.ups.com'
    LIVE_URL = 'https://onlinetools.ups.com'
```

It should pick `LIVE_URL` by default, unless you pass `:test => true` as an option to the method.
