### ISSUE TITLE
Extract Quantified as gem

### ISSUE THREAD

**Issue by wvanbergen** [Shopify/active_shipping#227]
Right now we have vendored *Quantified* in this library. I porpose to extract this into a separate gem, and add it as an external dependency. The name is still available: https://rubygems.org/gems/quantified

@Shopify/shipping thoughts?

**Comment by kmcphillips** [comment]
I'm completely behind that. It already has tests and a readme that would only need to be updated.

**Comment by wvanbergen** [comment]
https://github.com/Shopify/quantified/issues/1
