### ISSUE TITLE
Support for UPS Time in Transit / Accurate Estimated Delivery Dates

### ISSUE THREAD

**Issue by eboswort** [Shopify/active_shipping#242]
Hi,

I brought this up a few months back on the google group but nobody ever responded to me.

I've got support for the UPS time in transit API working on a fork of ActiveShipping and I'd love to merge that functionality back into shopify/active_shipping.

I'd like to get some feedback on how I could code this up in a way that other users of ActiveShipping would be down with because it's not totally straightforward. For one thing I'm not sure how this functionality is reflected in other carriers.

In the world of the UPS API, the Time in Transit API is the only way to get an accurate idea of when a shipment will arrive based on the day you send it, the origin and the destination. 

The current implementation of get_rates for UPS will give you a delivery_range and a delivery_date for UPS, but these are pretty inaccurate. They are based on the GuaranteedDaysToDelivery field that is returned by UPS's rating API. But that field doesn't take origin, destination, or pickup date into account. So for UPS ground it will always return 5 because that is the max number of days that UPS ground takes for any origin/destination. This ignores the fact that for any particular origin zipcode, most of the continental United States can be reached in less than 5 days (http://www.ups.com/maps). 
The current calculation of delivery_range/delivery_date also ignores holidays and can sometimes underestimate the delivery time for packages that will actually take more than 5 weekdays.

The time in transit API solves these problems. You tell it your origin, destination and pickup date, it tells you the expected delivery date for each service level. It takes holidays into account. And can help you decide to use a cheaper option like UPS ground, when that option will end up getting the shipment there just as fast as a more expensive one.

So like I said I would like to write up a PR adding support for the UPS time in transit API to shopify/active_shipping.

I could see this working in two ways. 

There could be a new method on carrier called get_delivery_dates (or some better name). This is how I have this functionality implemented in my fork. It returns a DeliveryDatesResponse object which has an array of delivery_date_estimates, one for each service. It's a similar set up to the get_rates stuff. This is working fine for me. I guess the only potential problem is if this functionality doesn't make any sense for any other carriers then maybe it's not so great to have on the carrier class? I could implement it directly on the UPS class. Is there a general active_shipping policy for carrier specific functionality?

Another option would be to implement support for an option passed into get_rates that was like accurate_delivery_estimates => true, which for UPS would cause it to calculate the rates the same way it does now, but then also hit the Time in Transit API and fill in the delivery_ranges of those RateEstimates with more accurate estimated delivery dates.

Or maybe someone has a suggestion for a 3rd way of adding support for UPS Time in Transit?

Hopefully accurate delivery estimates are something that other people using active_shipping are interested in. I'm trying to get my company off of our fork and onto shopify/active_shipping and we need accurate delivery date estimates.

I would prefer the first option, since I don't really like the idea of 2 api calls in response to one get_rates request.

**Comment by wvanbergen** [comment]
(I should have read this before checking out the PR, oh well)

I think as an end goal I prefer the second option instead of the first one, as long as it's opt in behavior. I can see three ways of doing that.

``` ruby

# 1
response = ups.find_rates(..., accurate_delivery_estimates: true) # does two API calls
p response.delivery_date # accurate without additional API calls

# 2
response = ups.find_rates(..., accurate_delivery_estimates: true) # does one API calls
p response.delivery_date # does one API call, accurate response

# 3
response = ups.find_rates(...) # does one API calls
p response.delivery_date # inaccurate response
p response.accurate_delivery_date # does one API call, accurate response
```

I know that we are looking into this for other carriers as well. @garethson, do you have thoughts about this?

**Comment by garethson** [comment]
This is great! I'd also prefer for us to remain flexible in people fetching just rates vs separate *accurate* delivery estimates. This one I don't think is really an option:
```ruby
p response.delivery_date # does one API call, accurate response
```
because the API returns a *list* of service estimates, we'd want to go into the delivery estimates response and find the matching service codes (UPS Ground, 1 Day Air, etc), and match up each record with its corresponding one in our rates response. We wouldn't ever want to do this for one record really and throw the rest away.

Are we OK with consuming API's doing:
```ruby
rates = ups.find_rates
delivery_estimates = ups.find_estimates
rates.each  do |rate|
  rate.delivery_date = find_matching_estimate_for_service_code(rate.code, delivery_estimates)
end
```
I feel like doing multiple calls behind this API would lead to more confusion.

**Comment by eboswort** [comment]
Perhaps there's a middle ground with a publicly exposed method allowing accurate delivery estimates to be fetched directly, but also an option to find_rates that causes both API calls to happen and there results to be merged into a RateResponse that has accurate delivery dates?

**Comment by garethson** [comment]
I like that. If we call the option `fetch_accurate_delivery_estimates` (vs `accurate_delivery_estimates `) so it's clear that a separate API call happening.

**Comment by eboswort** [comment]
Ok then. Sounds like we're circling in on something!
Unless anyone has objections, I'll go ahead and add a fetch_accurate_delivery_estimates option to find_rates in the PR that I already have up. That option will make use of get_delivery_dates (although I'm thinking maybe it should be called get_delivery_estimates) to merge accurate delivery dates into the rates response. 
But get_delivery_dates (get_delivery_estimates) will still be available to be called directly.

**Comment by garethson** [comment]
@eboswort I think we'd prefer to ship this PR mostly as is, ie: providing a way to fetch estimates in a separate call. And then let's add the `fetch_accurate_delivery_estimates` in a separate PR so we can better see what changes we're making there.

Thanks for helping out!

**Comment by eboswort** [comment]
Oh great. Then I'll just respond to comments on the PR

**Comment by llait** [comment]
@eboswort is this working now?
I have error when trying run your method
```
packages = [ActiveShipping::Package.new(64, [4, 8, 6], :units => :imperial, :value => 15300000, :description => 'Books')]

ups = ActiveShipping::UPS.new(:login => '1XXXXXXXXX66', :password => '5XXXXXXXXXX6', :key => '3XXXXXXXXXXX5')

origin = ActiveShipping::Location.new( :country => 'US',
                                       :state => 'CA',
                                       :city => 'Beverly Hills',
                                       :zip => '90210')

destination = ActiveShipping::Location.new( :country => 'CA',
                                            :province => 'ON',
                                            :city => 'Ottawa',
                                            :postal_code => 'K1P 1J1')

response = ups.get_delivery_date_estimates(origin, destination, packages)
ActiveShipping::ResponseError: Failure: Invalid Weight
	from /Users/AlxGol/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/active_shipping-1.0.0.pre4/lib/active_shipping/response.rb:26:in `initialize'
	from /Users/AlxGol/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/active_shipping-1.0.0.pre4/lib/active_shipping/delivery_date_estimates_response.rb:7:in `initialize'
	from /Users/AlxGol/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/active_shipping-1.0.0.pre4/lib/active_shipping/carriers/ups.rb:777:in `new'
	from /Users/AlxGol/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/active_shipping-1.0.0.pre4/lib/active_shipping/carriers/ups.rb:777:in `parse_delivery_dates_response'
	from /Users/AlxGol/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/active_shipping-1.0.0.pre4/lib/active_shipping/carriers/ups.rb:191:in `get_delivery_date_estimates'
	from (irb):20
	from /Users/AlxGol/.rbenv/versions/2.2.0/bin/irb:11:in `<main>'

```

**Comment by eboswort** [comment]
Yes sorry! International shipments require a weight element to work. I added this element my fork but I haven't done a PR back to active_shipping yet because I didn't have time to write tests.

This is the change that will make an international request work:
https://github.com/CasperSleep/active_shipping/commit/b4e06e886d85e6a3930c2682d1266dfb4473ab1b

I intend to do a PR back to active_shipping, but if you're in a rush you could fork and apply that commit. Or if you're interested you could cherry-pick that commit and add the code above as a test and then do a PR back to active shipping yourself.

**Comment by llait** [comment]
@eboswort thanks!

**Comment by sparklingsparklers** [comment]
UPS Time In Transit is exactly what I've been trying to integrate onto my Shopify shipping method page!

**Comment by eboswort** [comment]
Closing this since this feature is merged
