### ISSUE TITLE
Tracking FedEx International Package

### ISSUE THREAD

**Issue by ZachGreen-ShipOffers** [Shopify/active_shipping#263]
I have no problem tracking US orders using the gem but as soon as i put in an international tracking number a undefined method `text' for nil:NilClass error gets thrown. also I did not find any place where I could distinguish between international and US shipments.

May be a bug may be me thanks in advanced

**Comment by wvanbergen** [comment]
Can you supply a stack trace, and a code snippet?

**Comment by ZachGreen-ShipOffers** [comment]
Actually I forked the repo and going to send a pull request. it was an easy fix just had to tweak one thing under the hood

**Comment by wvanbergen** [comment]
Awesome :+1:
