### ISSUE TITLE
USPS - RECTANGULAR is an invalid container type for a REGULAR package and ALL service.

### ISSUE THREAD

**Issue by rdaniels** [Shopify/active_shipping#275]
I'm getting the following error when trying to find_rates for USPS, any ideas?

     ActiveShipping::ResponseError:
       RECTANGULAR is an invalid container type for a REGULAR package and ALL service.

origin.to_s
=> "Lansing, MI, 48910 United States"
destination.to_s
=> "Tampa, FL, 33609 United States"
packages.to_s
=> "[#<ActiveShipping::Package:0x00000103f8ec98 @options={:units=>:imperial}, @dimensions=[#<Quantified::Length: 10 inches>, #<Quantified::Length: 10 inches>, #<Quantified::Length: 10 inches>], @weight_unit_system=:imperial, @dimensions_unit_system=:imperial, @weight=#<Quantified::Mass: 96.0 ounces>, @value=nil, @currency=nil, @cylinder=false, @gift=false, @oversized=false, @unpackaged=false, @inches=[10, 10, 10]>]"

**Comment by trishume** [comment]
Just experienced this error as well, investigating.

**Comment by trishume** [comment]
This regression was caused by https://github.com/Shopify/active_shipping/pull/248 not reading the USPS spec properly. [This](https://www.usps.com/business/web-tools-apis/rate-calculator-api.htm) specifically says to leave it blank when it is not a large package
