### ISSUE TITLE
FedEx meter value

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/active_shipping#295]
Where in the setup for FedEx credentials is the meter number used?

I get 

    response = fedex.find_rates(origin, destination, packages)
    ActiveShipping::ResponseError: ERROR - 803: Meter number is missing or invalid.

**Comment by philsmy** [comment]
I had the same problem but looking in the code I see that 'login' in the fedex module is actually your meter number. Of course, for some reason I am getting the '1000 failed authentication error' back...so maybe I have the other values wrong!

**Comment by resistorsoftware** [comment]
It worked for me with the login and meter number. I did the same thing, reviewed the code and found that generated the right call.

**Comment by andrewshatnyy** [comment]
@philsmy thanks for clearing that out!

"FEDEX LOGIN:" is actually FEDEX METER:
