### ISSUE TITLE
USPS: commercial_base: true fails on international rate requests

### ISSUE THREAD

**Issue by mfvargo** [Shopify/active_shipping#303]
If I set the option commercial_base: true on find_rates or when I create the Carrier with the option commercial_base: true the API gives an error when sending the IntlRateV2Request to the USPS.  I see this when I set the logger on the carrier object.  If I don't set commercial_base: true the api works fine.

USPS is rejecting the request with the error

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Number>-2147221202</Number><Source>Common:XmlParse</Source>
<Description>
The element 'Package' has invalid child element 'OriginZip'. List of possible elements expected: 'CommercialPlusFlag, ExtraServices, AcceptanceDateTime, DestinationPostalCode, RatePriceType, RatePaymentType, Content'.
</Description><HelpFile/><HelpContext/></Error>
```
I put some debug in the world_rates() function to see the request (Love the Nokogiri switch!)  and it looks like this
```ruby
  def world_rates(origin, destination, packages, options = {})
    request = build_world_rate_request(origin, packages, destination, options)
    puts request.to_s
    # never use test mode; rate requests just won't work on test servers
    parse_rate_response(origin, destination, packages, commit(:world_rates, request, false), options)
  end
```
and I see this (I did the "XXXXXXXX" on userid)
```xml
<?xml version="1.0"?>
<IntlRateV2Request USERID="XXXXXXXXXXXX">
  <Revision>2</Revision>
  <Package ID="0">
    <Pounds>0</Pounds>
    <Ounces>8</Ounces>
    <MailType>Package</MailType>
    <GXG>
      <POBoxFlag>N</POBoxFlag>
      <GiftFlag>N</GiftFlag>
    </GXG>
    <ValueOfContents>0.0</ValueOfContents>
    <Country>Canada</Country>
    <Container>RECTANGULAR</Container>
    <Size>LARGE</Size>
    <Width>11.81</Width>
    <Length>14.76</Length>
    <Height>1.05</Height>
    <Girth>25.72</Girth>
    <CommercialFlag>Y</CommercialFlag>
    <OriginZip>94063</OriginZip>
    <AcceptanceDateTime>2015-07-08T00:12:07Z</AcceptanceDateTime>
    <DestinationPostalCode>V0E 1B4</DestinationPostalCode>
  </Package>
</IntlRateV2Request>
```

So the CommercialFlag is in there just before it is bitching about OriginZip.  So for fun I monkeypatched the build_world_rate_request() function to just put that at the end of the <Package> and I get a different text but same error.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Number>-2147221202</Number><Source>Common:XmlParse</Source>
<Description>
The element 'Package' has invalid child element 'CommercialFlag'. List of possible elements expected: 'RatePriceType, RatePaymentType, Content'.
</Description><HelpFile/><HelpContext/></Error>
```
When it sends this request (same as before just moved the CommercialFlag to the end)
```xml
<?xml version="1.0"?>
<IntlRateV2Request USERID="XXXXXXXXX">
  <Revision>2</Revision>
  <Package ID="0">
    <Pounds>0</Pounds>
    <Ounces>8</Ounces>
    <MailType>Package</MailType>
    <GXG>
      <POBoxFlag>N</POBoxFlag>
      <GiftFlag>N</GiftFlag>
    </GXG>
    <ValueOfContents>0.0</ValueOfContents>
    <Country>Canada</Country>
    <Container>RECTANGULAR</Container>
    <Size>LARGE</Size>
    <Width>11.81</Width>
    <Length>14.76</Length>
    <Height>1.05</Height>
    <Girth>25.72</Girth>
    <OriginZip>94063</OriginZip>
    <AcceptanceDateTime>2015-07-08T00:02:59Z</AcceptanceDateTime>
    <DestinationPostalCode>V0E 1B4</DestinationPostalCode>
    <CommercialFlag>Y</CommercialFlag>
  </Package>
</IntlRateV2Request>
```
I get this error for all international destinations, not just Canada.  I still have production code using 0.12.5 with commercial_base: true on international without problems except for the ServiceCode="2" issue to Canada gives a price of $0.00. (which is why I upgraded to 1.4.1 to start with) LOL

I don't want to deploy this code because it will end up charging all our international customers about 10% more for shipping.  Smells like a USPS api problem but I don't even know how to deal with that.

**Comment by mfvargo** [comment]
As a workaround for this, I just added a modifier on the various shipping options to apply a fixed discount on a per option basis..  It seems 10% off on First-Class package international, 6.5% off on Priority International and 13% on Priority International Express matches the commercial prices.  I tried this on destinations to Europe, Canada, and Australia and got the same results by applying these discounts that I did using the 0.12.5 gem with the commercial flag set.

**Comment by mleglise** [comment]
Just figured it out. The OriginZip field needs to appear right before the CommercialFlag, not after. The [USPS API](https://www.usps.com/business/web-tools-apis/rate-calculator-api.htm) cares about the order of XML elements, and making that position change fixes it. I'll put together a pull request.
