### ISSUE TITLE
How to get started with Canada Post

### ISSUE THREAD

**Issue by olimart** [Shopify/active_shipping#337]
Hi,
thanks for your work on active_shipping. I'm trying to get started with Canada Post.

I can't find how to authenticate with Canada Post.

I found login method in the code but not sure what is expected.
`canada_post = ActiveShipping::CanadaPost.new(login: ???)`

I tried passing API Key Number (username : password) from my Canada Post account but no luck so far.

What credentials is expected?

**Comment by megetron** [comment]
did you solve it out? I have troubles starting with canadaPost, I got from canada post user:password format but the credentials on active_shipping is login (one single input for username and not password...)
I have notice there is also canada_post_pws file, not sure what the differences between both.

**Comment by olimart** [comment]
@megetron I gave up. Now using this gem https://github.com/shipppit/shipppit-canada-post

**Comment by megetron** [comment]
Thanks @olimart for response.

I have contact this carrier support and it seems like active_shipping CanadaPost implementation is the old work flow of the carrier.

The new way to connect to Canada Post is the implementation made by active_shipping with CanadaPostPWS.

I still have difficulties getting a key for their API. According to their support Shopify needs to provide such key for their merchants...

Now, I am not a shopify merchant but I do use shopify active_shipping libarary to simplify and unify the work with several carriers in parallel.

So, currently I am stuck here getting permission keys for CanadaPost API so will wait for their response or else someone here familiar with the process.

**Comment by olimart** [comment]
@megetron shipppit-canada-post reflects the latest from Canada Post. You can get started by signing up as 'developer' through their site. Some actions require a valid 'platform-enabled' account though
