### ISSUE TITLE
pickup_time returns as nil for all rates

### ISSUE THREAD

**Issue by megetron** [Shopify/active_shipping#355]
I am building app that compare rates between carriers and now testing the active_shipping solution.

After playing with it a while, I could get rates as expected, but have notice that the very important variable pickup_time always nil and delivery range has the same dates (e.g. 4.4.2016 - 4.4.206) even for 3 days shipping..which is not really a range.

Just using fedex sandbox so this is not a production issue.
Someone know this issue?

**Comment by kmcphillips** [comment]
Missing a ton of detail here for anyone to be of any help to you. Request/response to start with.

I encourage you to dig into the payload you are receiving from the third party, see if the value you are expecting is there, then look at how it is unpacked in `fedex.rb`

**Comment by megetron** [comment]
Thanks, will do and let you know when done.
