### ISSUE TITLE
How do you send "Envelope" package?

### ISSUE THREAD

**Issue by megetron** [Shopify/active_shipping#358]
Great gem!
I could send a package now with weight and size. looks great. but what if I would like to send to a different package type something like envelope?
no size and weight is required here. and also I would like envelope rates only.

how to achieve that?
I think that short readme.txt of the gem is missing lots of explanations/examples this gem have, and I found the active_merchant group not so active.

Your help appreciated!

**Comment by kmcphillips** [comment]
Mostly this is a wrapper around various carriers. You can dig into the docs for your specific carrier and/or look at the carrier adapter file to get more information about package type specifics.
