### ISSUE TITLE
ActiveShipping::ResponseError: ERROR - 3907: Invalid Customs Value

### ISSUE THREAD

**Issue by Nitin-Salunke** [Shopify/active_shipping#364]
I'm getting the following error when I try to create a Fedex shipment in test mode.
I sent all the information but din't get to know what is this **customs value** and where to add it.

**Comment by kmcphillips** [comment]
Hey there.

I encourage you to dig into the FedEx docs, and to look at the payload of the request/response going between your environment and the FedEx servers.
