### ISSUE TITLE
Bad request: Your browser sent a query this server could not understand.

### ISSUE THREAD

**Issue by megetron** [Shopify/active_shipping#370]
Hi,
I am trying to get rates with that request:
`
    <?xml version=\"1.0\"?>
    <mailing-scenario xmlns=\"http://www.canadapost.ca/ws/ship/rate\">  
      <customer-number>0008450422</customer-number>  <quote-type>commercial</quote-type>  
      <parcel-characteristics>    
        <weight>0.001</weight>    
        <mailing-tube>false</mailing-tube>    
        <unpackaged>false</unpackaged> 
      </parcel-characteristics>  
      <origin-postal-code>10037</origin-postal-code>  
      <destination>    
        <united-states>      
          <zip-code>10001</zip-code>    
        </united-states>  
      </destination>
    </mailing-scenario>
`

Fork  project and debug lib/active_shipping/carriers/canada_post_pws.rb file get_rates function
response I get:
    "<HTML><HEAD><TITLE>Bad request</TITLE></HEAD>\n<BODY><H1>Bad request</H1>\nYour browser sent a query this server could not understand.\n</BODY></HTML>"

Can you please advice?

**Comment by kmcphillips** [comment]
Sorry, it’s not clear from this issue what the actual problem might be. 

ActiveShipping is a wrapper around third party APIs. We can't provide support for those APIs that we do not own. I'd encourage you to gather more detailed request information, consult the Canada Post documentation, and contact their technical support if you still are unable to make a request.

**Comment by megetron** [comment]
Yes, ActiveShipping is just a wrapper but shouldn't it work as a blackbox where you enter your credentials and find rates? If I would need to debug the active_shipping gem so it's kind of missing it's purpose right? :)

Anyway, once contact CandaPost support they asked me to send endpoint URL. they were suspect this is not their API response...
After debugging the gem, url in find_rates was: "https://soa-gw.canadapost.ca/rs/ship/price",according to canadaPost this is not a valid URL...

So....Now I am all confused here...The same code works just fine for fedex carrier.

Here is how I call them with active_shipping:

    canada_post = ActiveShipping::CanadaPostPWS.new(customer_number: "123456",  api_key: "my_login_id : my_password", secret: "my_password" ,:test => true)
    response = shipper.find_rates(origin, destination, packages)

Please ket me know what do you think,
