### ISSUE TITLE
How do you get the XML's response & request

### ISSUE THREAD

**Issue by megetron** [Shopify/active_shipping#377]
Can you please explain what the easiest way to get a response/request XML/JSON strings without debugging the code?
any logs for that? couldn't find it.

**Comment by kmcphillips** [comment]
Logging is the responsibility of the given adapters. You can look at the carrier you care about to see how it is logged. Or debug the request.

In general, reporting an issue should follow our guideline for contributing and should be well described problem with the code. Not simply a question.
