### ISSUE TITLE
NotImplementedError: #create_shipment is not supported by USPS.

### ISSUE THREAD

**Issue by jburks-bba** [Shopify/active_shipping#389]
Trying to create shipments and labels for USPS and I get a NotImplementedError. Any plans to implement create_shipment for USPS?

**Comment by kmcphillips** [comment]
Nope, nothing planned for a direct to USPS integration.

**Comment by shime** [comment]
@kmcphillips would you accept a PR that added that?

**Comment by kmcphillips** [comment]
@shime Sure thing. If it's well tested, supported documentation, etc..
