### ISSUE TITLE
 uninitialized constant Shipment::ActiveMerchant

### ISSUE THREAD

**Issue by cdeeg7293** [Shopify/active_shipping#391]
Any ideas what this could be?

**Comment by cdeeg7293** [comment]
uninitialized constant Shipment::ActiveMerchant

**Comment by cdeeg7293** [comment]
NameError in ShipmentsController#index

**Comment by kmcphillips** [comment]
This is not nearly enough information to file a bug report. Please include replication steps and a backtrace.
