### ISSUE TITLE
Replace Quantified with Measured

### ISSUE THREAD

**Issue by kmcphillips** [Shopify/active_shipping#427]
We have put a ton of work into [measured](https://github.com/Shopify/measured) and are using it throughout our projects at Shopify. 

[In the README](https://github.com/Shopify/measured#gem-quantified) we discuss all the reasons that `measured` provides more features and stability and reliability over `quantified`. So let's swap them out.

@thegedge @jonathankwok

**Comment by benwah** [comment]
Done here: https://github.com/Shopify/active_shipping/pull/450
