### ISSUE TITLE
FedEx Negotiated Rates returning nil

### ISSUE THREAD

**Issue by tdoganay** [Shopify/active_shipping#519]
I am trying to get negotiated rates from FedEx using: 

`shipper.find_rates(ActiveShipping::Location.new(ship_from), ActiveShipping::Location.new(ship_to), packages, negotiated_rates: true)`
where
`shipper = ActiveShipping::FedEx.new(login: 'xxxxxxxxx', password: 'xxxxxxxxxx', key: 'xxxxxxxxxxxxxxxx', account: 'xxxxxxxxx', test: false)`

The problem is that all the returned rates have a negotiated_rate of nil. I am able to get UPS negotiated rates using this same method. Is there something different that needs to be done when trying to get negotiated rates for FedEx?

**Comment by tdoganay** [comment]
After looking through both the ActiveShipping docs and the FedEx API docs, I've been able to conclude that ActiveShipping returns negotiated rates by DEFAULT and stores them in @total_price for each service type instead of @negotiated_rate.

**Comment by admin-it** [comment]
Had the same issue for UPS and this answer worked there as well.
