### ISSUE TITLE
Tests failing with Correios

### ISSUE THREAD

**Issue by ianzitow** [Shopify/active_shipping#551]
I'm trying to use this gem in my project, however the Brazilian carrier Correios is always returning this error during the execution of "bundle exec rake test:remote":

> ActiveShipping::ResponseError:         ActiveShipping::ResponseError: Column 'obsFim' does not belong to table FREIGHT_PRICE.

**Comment by Edouard-chin** [comment]
It seems like Correios had stopped supporting their endpoint and thus we removed support for Correios. Cf #556
